### ISSUE TITLE
Update 'script execution context' reference to refer to a `Bluetooth` instance

### ISSUE THREAD

**Issue by jyasskin** [WebBluetoothCG/web-bluetooth#196]
The spec currently refers to the [script execution context](https://html.spec.whatwg.org/multipage/webappapis.html#script-execution-environment) to make sure each bluetooth device, service, etc. only gets one `BluetoothDevice`, `BluetoothGattService`, etc. instance. However, that term no longer exists in HTML. @domenic suggests making one `BluetoothDevice`, etc. instance per [`Bluetooth`](https://webbluetoothcg.github.io/web-bluetooth/#bluetooth) instance instead, which exists once per global object, and looking it up based on the `this` argument to whatever method was called.

I believe the alternative is to look up the right `BluetoothDevice`, etc. instance on the [entry settings object](https://html.spec.whatwg.org/multipage/webappapis.html#entry-settings-object), which gives different, and I think less intuitive results if realm1 calls into realm2's navigator.bluetooth object. 

I think Chromium's current implementation effectively uses the entry settings object, but we'll try to change to match the spec.

@bzbarsky, does that all sound right? Is there any wording in WebIDL or elsewhere I should be using?

**Comment by bzbarsky** [comment]
> only gets one BluetoothDevice, BluetoothGattService, etc. instance.

@jyasskin I assume you mean "one instance per global", right?

I do think that using the global that the `Bluetooth` instance is associated with would make sense to use here.  The relevant IDL wording is precisely that.  http://heycam.github.io/webidl/#es-platform-objects says:

    Every platform object is associated with a global environment, just as the initial objects are.
    It is the responsibility of specifications using Web IDL to state which global environment (or, by
    proxy, which global object) each platform object is associated with. 

So your "extensions to the Navigator interface" section would define which global the returned `Bluetooth` instance is associated with and your definition of requestDevice (which I assume is the relevant API here) would look for an existing `BluetoothDevice` that matches whatever criteria and is associated with the same global, and if that doesn't exist, create it, and associate it with the global `this` is associated with. 

That said, since it sounds like you want to preserve its identity forever, you can probably just cache it in the `Bluetooth` instance so this all only matters in terms of defining the global the `BluetoothDevice` itself is associated with, right?
