### ISSUE TITLE
Treat devices as if they weren't bonded to websites that have access to them.

### ISSUE THREAD

**Issue by jyasskin** [WebBluetoothCG/web-bluetooth#226]
Per the thread at https://lists.w3.org/Archives/Public/public-web-bluetooth/2016Mar/0007.html, we'd like to have websites treat peripherals as if they're not bonded. That means that sites will need to re-discover services, characteristics, and descriptors after disconnecting, and they'll need to re-subscribe to notifications when they re-connect (#220), and might miss some that are fired between the connection and the re-subscription.

**Comment by krantik** [comment]
Re-subscribing to notifications after disconnect is fine, similar to how the browser caches content should it cache the services/characteristics/descriptors(scd's), at minimum it should fetch these values ahead instead of getting them when asked which will improve the experience in terms of timing and then monitor for changes.
