### ISSUE TITLE
Add Web Bluetooth API support to change MTU

### ISSUE THREAD

**Issue by beaufortfrancois** [WebBluetoothCG/web-bluetooth#284]
I've noticed Chrome OS and Android have different maximum transmission unit (MTU) when investigating https://bugs.chromium.org/p/chromium/issues/detail?id=643591 bug and I was wondering if we could add support for requesting an MTU size used for a given connection in the Web Bluetooth API.

Android already has this API which is really useful in my own opinion: https://developer.android.com/reference/android/bluetooth/BluetoothGatt.html#requestMtu(int)

For info, 23 bytes seems to be the default on Android while I can reach 512 bytes on Chrome OS.

WDYT?

**Comment by beaufortfrancois** [comment]
@Vudentz Is this something we could do in BlueZ?

**Comment by jyasskin** [comment]
I haven't investigated this in the BT spec yet, but why can't we auto-negotiate the largest supported MTU?

**Comment by beaufortfrancois** [comment]
In the short term, that would be nice indeed.

**Comment by Vudentz** [comment]
BlueZ actually attempts to do the maximum possible, our default per channel is actually 672 bytes given that comes from L2CAP, so in fact it can be over 512 bytes but usually the peripheral limits the MTU. As for exposing an API to set the MTU this is quite tricky because of the following:

1. The MTU shall only be negotiated once, so we might have to fail if that was already done previously.
2. MTU needs to be symmetric for input and output so it might be forced to be lower than the value required.
3. Usually the MTU is used to define application level fragmentation, stream/firmware transfers, etc. These are not very nice to be done over D-Bus and instead perhaps should done over e.g. a pipe passing a fd to the application where one can get the MTU of the connection and perhaps even lock the attribute so it is only accessed by that application using the fd. Note this type of application is abusing the ATT/GATT stack since the attributes were never meant to be used as stream endpoints, instead L2CAP Channels should have been used but it seems most OSes never implemented support for them leading to the current situation.

**Comment by beaufortfrancois** [comment]
For the sake of completeness, here are my findings regarding MTU size I've gathered from https://beaufortfrancois.github.io/sandbox/physical-web/fatbeacon/


Chrome OS | Android | Mac
 :---------------: | :-----------: | :------:
512 bytes | 20 bytes | 199 bytes
