### ISSUE TITLE
When disconnect is called, [[activeAlgorithms]] is being cleared twice

### ISSUE THREAD

**Issue by g-ortuno** [WebBluetoothCG/web-bluetooth#333]
Maybe just comment that Cleanup disconnected devices will stop pending connection requests.

**Comment by jyasskin** [comment]
Clearing `[[activeAlgorithms]]` in [step 1](https://webbluetoothcg.github.io/web-bluetooth/#dom-bluetoothremotegattserver-disconnect) serves to abort any active `connect()` calls. Step 2 returns early from this algorithm if the device isn't already connected, so we never get to [clean up the disconnected device](https://webbluetoothcg.github.io/web-bluetooth/#clean-up-the-disconnected-device) in that case. It might make sense to have [Clean up ...](https://webbluetoothcg.github.io/web-bluetooth/#clean-up-the-disconnected-device) return early for disconnected devices in order to remove the apparent redundancy. I haven't checked if that has any other unwanted side-effects.

Do you have a preference?

**Comment by g-ortuno** [comment]
I was trying to map this to the actual C++ code and it seemed weird to be clearing the map twice. I no longer think we should change anything.

**Comment by g-ortuno** [comment]
Ah I actually missed the purpose of Step 1 when implementing disconenct: http://crbug.com/684073
