### ISSUE TITLE
iBeacon is not detecting

### ISSUE THREAD

**Issue by rajeevnith** [WebBluetoothCG/web-bluetooth#335]
navigator.bluetooth.requestDevice is not detecting iBeacon (Ankhmaway Beacon iB001N & iB004N) in Google Chrome 54 (Mac OS X 10). Even though I have tried to filter all devices using https://googlechrome.github.io/samples/web-bluetooth/discover-services-and-characteristics.html. 

Are there requirements that bluetooth device (in my case Ankhmaway Beacon) needs to fulfil to be detectable in chrome browser using Web bluetooth API ? 
**FYI** in android we are able to detect our iBeacon using https://github.com/AltBeacon/android-beacon-library

**Comment by g-ortuno** [comment]
This seems like an issue with the Chrome implementation rather than a spec issue. In the future please use [http://crbug.com/new](http://crbug.com/new).

The website you point to tries to scan for all the devices by generating a list of name prefixes and scanning for them. This causes devices with no name to be filtered out.

Currently the Chrome Implementation only supports scanning for Service UUIDs and name/name prefix. iBeacon advertises Manufacturer Specific Data so for now there is no way to find it. The Spec does support filtering out by manufacturer data (and it even supports scanning for all devices) but that hasn't been implemented in Chrome yet. You can see a list of what's implemented in Chrome [here](https://github.com/WebBluetoothCG/web-bluetooth/blob/master/implementation-status.md#gatt-communication-api).
