### ISSUE TITLE
maplike handling is really weird

### ISSUE THREAD

**Issue by bzbarsky** [WebBluetoothCG/web-bluetooth#340]
There are various parts of this spec that attempt to define what the "map entries" are for maplikes in terms of a Map.  But maplikes already have a Map whose [[MapData]] is defined to be the "map entries".  See https://heycam.github.io/webidl/#es-maplike

So whatever you're doing with `[[data]]` right now should instead be done by manipulating the `[[BackingMap]]`, I would think.  And you need to specify exactly how you manipulate it, of course.

**Comment by jyasskin** [comment]
I don't know why I missed the `[[BackingMap]]` object that's available for this. Fix coming up.

**Comment by jyasskin** [comment]
Oh, maybe I was trying to specify against the [language-independent maplike spec](https://heycam.github.io/webidl/#idl-maplike), which says that "Prose accompanying the interface can describe how the map entries of an object change.", instead of the [ES binding](https://heycam.github.io/webidl/#es-maplike), which provides `[[BackingMap]]`. I'll still send the change to use the ES-specific slots, since I'm assuming ES elsewhere.

**Comment by bzbarsky** [comment]
You skipped the "you need to specify exactly how you manipulate it, of course" bit.  Filed https://github.com/WebBluetoothCG/web-bluetooth/issues/351 on that, I guess...
