### ISSUE TITLE
Write characterisctic to raspberry pi fails

### ISSUE THREAD

**Issue by borch84** [WebBluetoothCG/web-bluetooth#442]
Hi, I am working o a web application using web bluetooth api in order to connect a raspberry pi for writing some characteristic. 
If I write the characteristic value using nRF connect it works
![nRF-Connect](https://user-images.githubusercontent.com/15837742/59474208-2e0a8c00-8e03-11e9-9ee9-b541b2b4cbd3.jpeg)

But if I use the internal bluetooth interface from chrome browser it fails:
![rpi-bluetooth-error](https://user-images.githubusercontent.com/15837742/59474221-3fec2f00-8e03-11e9-8070-1e3a44b7627c.jpeg)

I cannot find how to get the error cause. I am able to use other bluetooth devices with my web application with no issues. 
Really appreciate if you could point me to the right direction. Thanks.

**Comment by reillyeon** [comment]
Please file an issue report on bugs.chromium.org so that Chromium developers can investigate this implementation issue. Please follow [the instructions](https://www.chromium.org/developers/how-tos/file-web-bluetooth-bugs) for Android to include logs with your report.

Closing this issue as implementation-specific. Feel free to comment with a link to the Chromium issue when it has been filed but do not re-open this issue.

**Comment by borch84** [comment]
hi @reillyeon I opened the chromium issue here: https://bugs.chromium.org/p/chromium/issues/detail?id=974103
Thanks.
