### ISSUE TITLE
Map to remove listing units

### ISSUE THREAD

**Issue by marcoscaceres** [WebBluetoothCG/web-bluetooth#49]
I don't have a concrete proposal, but feel something "map-like" might do the trick. This would handle all the look ups. Something like: 

```
[MapClass] interface BluetoothUnitMap{
void clear(); // clear only custom types, maybe?
boolean delete(BlueToothKey key); //as above?
void forEach(BTMapCallBack callback, optional any thisArg);
BlueToothUnit get(BlueToothKey key);
boolean has(BlueToothKey key);
BluetoothUnitMap set(BlueToothKey key, UUID128 value);
sequence<BlueToothKey> keys();
}

callback BTMapCallBack(UUID128 value, BlueToothKey key, BluetoothUnitMap object);

typedef DOMString UUID128; //force it to conform to canonical form in prose. 
typedef CustomBlueToothKey DOMString; 
typedef (StandardBlueToothKey or CustomBlueToothKey)  BlueToothKey; 

enum StandardBlueToothKey{
   "energy.kilogram_calorie",
   ...
}
```

**Comment by jyasskin** [comment]
@esprehn suggested moving toward something like `Bluetooth.getService('heart_rate')` and avoiding `navigator.bluetooth` entirely.

`Bluetooth.getService('uuid_alias')` collides with `getService('instanceId')`, so maybe `BluetoothUUID.getService('uuid_alias')` or `BluetoothService.uuidFor('uuid_alias')`.

We could also do `Bluetooth.uuidFor('service.heart_rate')`, making people include the type prefix that https://developer.bluetooth.org/gatt/services/Pages/ServicesHome.aspx uses. Since we can avoid the type prefix in uses like `Bluetooth.requestDevice({filters: [{services: ['heart_rate']}]})`, I'm leaning toward `BluetoothUUID.getService('uuid_alias')`.

**Comment by kenchris** [comment]
That would make the API useful for Node.js as well. We should probably do the same for Web NFC then @zolkis

**Comment by scheib** [comment]
Moving off navigator sounds fine, but is separate from moving from uuids.service.heart_rate to BluetoothUUID.getService('heart_rate'). I'd prefer something like BluetoothUUIDs.service.heart_rate for the ease of development and auto completion within DevTools, and because it feels like a const data value I should be able to access from an attribute, and shouldn't need to call a method for.

**Comment by esprehn** [comment]
That's not idiomatic JS, it would be HEART_RATE then, and the .service is pretty weird but I suppose you can do that. It means allocating this service object for every context and creating a BluetoothService interface only for the purpose of constants. This thing is conceptually a map, you want a way to go from UUID -> Name, and from Name -> UUID. You probably also want a way to register new names? In either case you don't want navigator.bluetooth.uuids.{...}, constants shouldn't be on your instance.

I'd suggest navigator.bluetooth.requestDevice since that's talking to the browser's bluetooth system, just like the other device capability APIs. The object model for your system should just be interfaces on the window though, and you can put static constants there.

In general I'd encourage you to study the other device capability APIs and try to be consistent. :)

**Comment by jyasskin** [comment]
https://www.khronos.org/registry/webgl/specs/1.0/#WebGLRenderingContextBase endorses both ALL_CAPS attributes for constants and consistency with an [external specification](https://www.khronos.org/registry/gles/specs/2.0/es_full_spec_2.0.25.pdf) (that itself uses ALL_CAPS), rather than a mapping function. Other than that, I don't see a [device capability API](http://www.w3.org/2009/dap/) that needs to interoperate with externally-defined constants, especially the unreadable UUID constants that Bluetooth uses.

Nonetheless, for this API, just about every web platform expert I've talked to has preferred a mapping function on some `BluetoothXyz` interface, so it doesn't seem worthwhile to try to argue for anything else.

For `requestDevice`, the most similar proposal is [SerialPort.requestList()](http://whatwg.github.io/serial/#serialport-interface), but several others use `navigator.Xyz()` ([navigator.vibrate()](http://www.w3.org/TR/vibration/#vibration-interface), [navigator.getBattery()](http://www.w3.org/TR/battery-status/#the-navigator-interface), [navigator.mediaDevices.enumerateDevices()](http://w3c.github.io/mediacapture-main/getusermedia.html#mediadevices) so @esprehn's advice to keep what we have seems fine.
