### ISSUE TITLE
API to facilitate the grabbing of all primary services `getAllPrimaryServices`

### ISSUE THREAD

**Issue by enahsor** [WebBluetoothCG/web-bluetooth#507]
Hi. I think there should be a way to get all primary services attached to a device. I'm surprised this doesn't exist already.
I'm pretty new to this API and the only way I could figure out how to get services for a device is via `chrome://bluetooth-internals/#devices`. I don't particularly like that approach as it requires me to know the device beforehand.
eg
```
server.getAllPrimaryServices()
```
or 

```
device.getAllPrimaryServices()
```

**Comment by reillyeon** [comment]
An API like that would be of little utility because the developer needs to specify up front the set of services they would like to access when calling `navigator.bluetooth.requestDevice()`.

Chrome's internals page can enumerate the full set of services, while a site cannot, because it is a privileged component of the browser.
