### ISSUE TITLE
[Scanning] advertisementReceived on Bluetooth not specified

### ISSUE THREAD

**Issue by motla** [WebBluetoothCG/web-bluetooth#512]
Hi,

In [Example 1 of the Web Bluetooth Scanning](https://webbluetoothcg.github.io/web-bluetooth/scanning.html#example-ibeacon) specification, you use:

```javascript
navigator.bluetooth.addEventListener('advertisementreceived', event => { ... });
```

However `advertisementreceived` event is only specified for device objects, not the Bluetooth instance. `navigator.bluetooth` has only one event which is `availabilitychanged` event.

So how should we implement it? I guess any `advertisementreceived` fired on a device object should then (or before) fire `advertisementreceived` on its Bluetooth instance as well.

##### IMO TODO:
- [ ] Add a line that explains when `advertisementreceived` should be fired on the Bluetooth instance (either at https://webbluetoothcg.github.io/web-bluetooth/scanning.html#advertising-events or https://webbluetoothcg.github.io/web-bluetooth/#advertising-events)
- [ ] Update Bluetooth definition with the `advertisementreceived` event and description at https://webbluetoothcg.github.io/web-bluetooth/#bluetooth

What do you think?

This issue was already mentioned in #426 and has only been partially fixed.

**Comment by reillyeon** [comment]
#427 fixes this completely because Bluetooth includes BluetoothDeviceEventHandlers. The [Responding to advertising events](https://webbluetoothcg.github.io/web-bluetooth/scanning#advertising-events) steps use the [fire and advertisementreceived event](https://webbluetoothcg.github.io/web-bluetooth/#fire-an-advertisementreceived-event) steps, which creates a bubbling event which will bubble from BluetoothDevice to Bluetooth according to the [Bluetooth tree](https://webbluetoothcg.github.io/web-bluetooth/#bluetooth-tree).
