### ISSUE TITLE
Not working with MacOS Sonoma + Intel

### ISSUE THREAD

**Issue by darrikonn** [WebBluetoothCG/web-bluetooth#615]
Web Bluetooth is not working for Macs with Sonoma and Intel processor.
```typescript
const device = navigator.bluetooth.requestDevice({filters: [...]})
const gattService = await device.gatt.connect()  // <-- this fails
```

When connecting the end users receive:
```
Uncaught (in promise) DOMException: GATT Server is disconnected.
Cannot retrieve services. (Re)connect first with `device.gatt.connect`.
```

This worked before upgrading to Sonoma on the Intel laptop.
Using the M* chips with Sonoma works fine.

**Comment by dlech** [comment]
This repository is for the specification, not the implementation. Please see https://www.chromium.org/developers/how-tos/file-web-bluetooth-bugs/ for info on how to report bugs with the implementation. Since this was due to an OS upgrade, it would probably be a good idea to file a regression report with Apple as well.
